// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNPQs-KgFP-yHPw1hmVYhWcckf8FWvwfo',
    appId: '1:543999354803:web:bae8c74d049faa69190dc6',
    messagingSenderId: '543999354803',
    projectId: 'foodcore-1ac89',
    authDomain: 'foodcore-1ac89.firebaseapp.com',
    storageBucket: 'foodcore-1ac89.appspot.com',
    measurementId: 'G-W16Y9ZKJG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUp6sGsNhx7oH95IWbnfTYPAmsWn75vRw',
    appId: '1:543999354803:android:8e8db1ae3103b0dd190dc6',
    messagingSenderId: '543999354803',
    projectId: 'foodcore-1ac89',
    storageBucket: 'foodcore-1ac89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3fTVf5E8pTBDZI_BerFYegnhO-hoZUyM',
    appId: '1:543999354803:ios:bbaaca8ed9a989e1190dc6',
    messagingSenderId: '543999354803',
    projectId: 'foodcore-1ac89',
    storageBucket: 'foodcore-1ac89.appspot.com',
    iosClientId: '543999354803-c4n9lh94p41s698ii0h3ah2n8cuhie37.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodcore',
  );
}
